
Currently Loaded Modules:
  1) anaconda3/2019.11-gpu

 

Loading cached dataset...
Traceback (most recent call last):
  File "rescore.py", line 114, in <module>
    with open(os.path.join(args.work_dir + model_dir + '/', 'model.pt'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/work/moisioa3/conv_lm/transformer-xl/pytorch/LM-TFM-wdtrain20200807-113927/model.pt'
