
Currently Loaded Modules:
  1) anaconda3/2019.11-gpu

 

Loading cached dataset...
Traceback (most recent call last):
  File "rescore.py", line 121, in <module>
    with open(os.path.join(args.work_dir, model_dir, 'model.pt'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/LM-TFM-wdtrain/20200811-133946-55045847/model.pt'
